# SPDX-License-Identifier: Apache-2.0

name: $(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.rrr)
trigger:
- master
pr:
- master

variables:
  GOPATH: $(Agent.BuildDirectory)/go
  PATH: $(Agent.BuildDirectory)/go/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin
  GO_VER: 1.13.8
  NODE_VER: 10.19

jobs:
- job: TestsWithCoverage
  pool:
    vmImage: ubuntu-16.04
  steps:

  - template: install_deps.yml
  - checkout: self
  - script: |
      npm config set prefix ~/npm
      npm install
      npm run test
      cd ./client && npm install
      echo "--------> npm tests with code coverage"
      npm run test:ci -- -u --coverage && npm run build
    displayName: Run Tests With Coverage Report
  - script: |
      cd client
      wget https://raw.github.com/eriwen/lcov-to-cobertura-xml/master/lcov_cobertura/lcov_cobertura.py
      python lcov_cobertura.py ./coverage/lcov.info
    displayName: Create Cobertura Report
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: $(System.DefaultWorkingDirectory)/client/coverage.xml
      pathToSources: $(System.DefaultWorkingDirectory)/client

- job: SanityChecks_v1_4
  pool:
    vmImage: ubuntu-16.04
  steps:
  - template: install_deps.yml
  - checkout: self
  - script: |
      npm install
      npm run e2e-api-test-v1
    displayName: Run Sanity Checks for v1.4

- job: SanityChecks_v2_1
  pool:
    vmImage: ubuntu-16.04
  steps:
  - template: install_deps.yml
  - checkout: self
  - script: |
      npm install
      npm run e2e-api-test-v2
    displayName: Run Sanity Checks for v2.1

- job: GUITests_v1_4
  pool:
    vmImage: ubuntu-16.04
  steps:
  - template: install_deps.yml
  - checkout: self
  - script: |
      npm install
      npm run e2e-gui-test-v1
    displayName: Run GUI Tests for v1.4

- job: GUITests_v2_1
  pool:
    vmImage: ubuntu-16.04
  steps:
  - template: install_deps.yml
  - checkout: self
  - script: |
      npm install
      npm run e2e-gui-test-v2
    displayName: Run GUI Tests for v2.1
  