# SPDX-License-Identifier: Apache-2.0

name: $(SourceBranchName)-$(Date:yyyyMMdd)$(Rev:.rrr)
trigger:
- master
pr:
- master

variables:
  GOPATH: $(Agent.BuildDirectory)/go
  PATH: $(Agent.BuildDirectory)/go/bin:/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin:/usr/local/sbin
  GO_VER: 1.13.8
  NODE_VER: 10.19

jobs:
- job: TestsWithCoverage
  pool:
    vmImage: ubuntu-16.04
  steps:

  - template: install_deps.yml
  - checkout: self
  - script: |
      npm config set prefix ~/npm && npm install -g mocha
      npm install chai && npm install
      cd app/test && npm install
      npm run test
      cd ../../client && npm install
      echo "--------> npm tests with code coverage"
      npm run test:ci -- -u --coverage && npm run build
    displayName: Run Tests With Coverage Report
  - script: |
      cd client
      wget https://raw.github.com/eriwen/lcov-to-cobertura-xml/master/lcov_cobertura/lcov_cobertura.py
      python lcov_cobertura.py ./coverage/lcov.info
      mv $(System.DefaultWorkingDirectory)/app/test/*.js $(System.DefaultWorkingDirectory)/client
    displayName: Create Cobertura Report
  - script: npx cobertura-merge -o output.xml package1=$(System.DefaultWorkingDirectory)/app/test/coverage/cobertura-coverage.xml package2=$(System.DefaultWorkingDirectory)/client/coverage.xml
    displayName: Merge Cobertura Reports
  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: 'Cobertura'
      summaryFileLocation: $(System.DefaultWorkingDirectory)/output.xml
      pathToSources: $(System.DefaultWorkingDirectory)/client

- job: SanityChecks
  pool:
    vmImage: ubuntu-16.04
  steps:
  - template: install_deps.yml
  - checkout: self
  - script: |
      npm install
      npm run e2e-api-test:ci
    displayName: Run Sanity Checks

- job: GUITests
  pool:
    vmImage: ubuntu-16.04
  steps:
  - template: install_deps.yml
  - checkout: self
  - script: |
      npm install
      npm run e2e-gui-test:ci
    displayName: Run GUI Tests
